@startuml autocatalogs
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml


System_Boundary(https, "Сторонние сайты") {
System(avitoCatalog, "Авито", "сайт обьявлений")
}

System_Boundary(Autocatalogs, "Автокаталог") {

System(autocatalogs, "autocatalogs", "Автокаталог")
System(service1, "service1", "service1")
System(service2, "service2", "service2")
System(service3, "service3", "service3")
System(service4, "service4", "service4")
System(service5, "service5", "service5")
System(service6, "service6", "service6")

ContainerDb(autocatalogsdb, "База данных", "MySQL/Postgres SQL", "Содержит данные о авто(марка, модель, кузов, руль, трансмиссия)", $sprite="msql_server")


Rel(autocatalogs, autocatalogsdb, "")

Rel(autocatalogs, avitoCatalog,"")
Rel(autocatalogs, service1,"")
Rel(autocatalogs, service2,"")
Rel(autocatalogs, service3,"")
Rel(autocatalogs, service4,"")
Rel(autocatalogs, service5,"")
Rel(autocatalogs, service6,"")

}

@enduml